version: '3.8'

services:
  cognitive-tests:
    build: .

    container_name: cognitive-tests-prod

    ports:
      - "8001:8001"

    volumes:
        - .:/usr/src/app

    env_file:
    
      - .env
    restart: unless-stopped