name: CI/CD Docker Deployment for Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, docker-deploy-iq-test-matrics]
    
    env:
      DEPLOY_DIR: ${{ secrets.DEPLOY_SCRIPT_PATH }} # Access the path from a GitHub Secret

    steps:
      - name: Checkout Code
        # Changed 'actions:checkout@v4' to 'actions/checkout@v4'
        uses: actions/checkout@v4

      - name: Set Script Permissions and Run Deployment
        run: |
          echo "Deployment Directory: $DEPLOY_DIR"
          
          # 1. Set Permissions
          chmod +x $DEPLOY_DIR/stop-prod.sh
          chmod +x $DEPLOY_DIR/deploy-prod.sh
          
          # 2. Run Deployment
          echo "Executing deployment via scripts..."
          $DEPLOY_DIR/stop-prod.sh
          $DEPLOY_DIR/deploy-prod.sh
          
          echo "Deployment complete. Services are restarting."
